### ISSUE TITLE
Mark and unmark multiple tasks (visual mode)

### ISSUE THREAD

**Issue by vaga** [cweagans/vim-taskpaper#7]
You can add this lines in ftplugin file to mark and unmark multiple tasks:
```
vnoremap <buffer> <Leader>td :norm <Leader>td<CR>
vnoremap <buffer> <Leader>tt :norm <Leader>tt<CR>
vnoremap <buffer> <Leader>tx :norm <Leader>tx<CR>
```

And you could add more key mappings with visual mode like move multiple tasks (`<Leader>tm`) and archive/unarchive multiple tasks simultaneous.

Thanks for the plugin! 👍

**Comment by cweagans** [comment]
Added in 8555769fcef550d711dad1b586162a2196dd0207

Thanks!
